### PR TITLE
WebSocket for Counter game

### PR DESCRIPTION
**Pull request by afg419**
This PR follows the backend portion of http://www.phoenixframework.org/docs/channels to set up a channel in our Phoenix server.  We also create a counter model which will be incremented by messages through the channel.

### CODE REVIEW

**Comment by rrgayhart** [comment]
#yolo

**Comment by brantwellman** [comment]
Not sure how much of this I understand, if any really.

I see you have a method commented out `def handleout`, I'm guessing you might be saving that for later.

**Comment by afg419** [comment]
Thanks for pointing out those comments Brant.  I'm going to hold onto them for now just cause I might need that method later, and don't want to dig back into the tutorial to get it again.  Really though, good catch.

**Comment by brantwellman** [comment]
:+1:

**Comment by rrgayhart** [comment]
This repo name makes me sing Everybody Hurts in my head - which is a good thing

**Comment by hectorhuertas** [comment]
Nice start!

You changed the postgres adapter credentials from 'posgres' to 'aarongreenspan'. Is it for any specific reason or just to make it work in your system? (i didn't need to)

:+1:

**Comment by afg419** [comment]
I kept getting an error that postgres user role isn't defined.  I've had that problem in all my phoenix apps, almost definitely something I need to do with postgres independent of Phoenix

**Pull request merged**
